---
- name: Установка qemu-guest-agent на Debian и Ubuntu
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: true
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- name: Установка qemu-guest-agent на RHEL и CentOS
  yum:
    name: qemu-guest-agent
    state: present
  when: ansible_facts['distribution'] in ["RedHat", "CentOS"]

- name: Включение и запуск qemu-guest-agent
  systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
