---
- name: Update GRUB
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: ansible_os_family == "RedHat"

- name: Update GRUB (Debian-based)
  command: update-grub
  when: ansible_os_family == "Debian"

- name: Reboot Server
  reboot:
    msg: "Rebooting to apply SELinux changes"
    reboot_timeout: 600
