---
- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Create directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    owner: root
    group: root
    validate_certs: yes
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Dearmor Docker GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
    creates: /etc/apt/keyrings/docker.gpg
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Set correct architecture for Docker repository
  ansible.builtin.set_fact:
    docker_architecture: "{{ ansible_architecture | regex_replace('x86_64', 'amd64') | regex_replace('aarch64', 'arm64') }}"
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Add Docker repository to APT sources
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: yes
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Ensure Docker service is enabled and started
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Add user to docker group (optional)
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Debian']
