---
- name: Настраиваем Wazuh (добавляем ClamAV в логи)
  lineinfile:
    path: /var/ossec/etc/ossec.conf
    insertafter: "</localfile>"
    line: |
      <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/clamav.log</location>
      </localfile>
  notify: Перезапустить Wazuh Agent
