---
- name: Install Postfix
  package:
    name: postfix
    state: present

- name: Copy Postfix configuration file
  template:
    src: "main.cf.j2"
    dest: "/etc/postfix/main.cf"
  notify:
    - Restart Postfix

- name: Ensure Postfix is started and enabled
  service:
    name: postfix
    state: started
    enabled: yes
