---
- name: Install Fail2Ban
  package:
    name: fail2ban
    state: present

- name: Configure Fail2Ban for SSH Protection
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart Fail2Ban
