all:
  vars:
    ansible_ssh_user: skoptilin
    ansible_ssh_private_key: "/home/skoptilin/.ssh/id-rsa"
  children:
    sdsevo:
      hosts:
        int-sdsevo-app1:
          ansible_host: 172.20.101.40
        int-sdsevo-app2:
          ansible_host: 172.20.101.41
        int-sdsevo-cache1:
          ansible_host: 172.20.101.53
        int-sdsevo-cache2:
          ansible_host: 172.20.101.54
        int-sdsevo-cache3:
          ansible_host: 172.20.101.55
        int-sdsevo-cdn1:
          ansible_host: 172.20.101.44
        int-sdsevo-cdn2:
          ansible_host: 172.20.101.45
        int-sdsevo-dwh1:
          ansible_host: 172.20.101.52
        int-sdsevo-lb1:
          ansible_host: 172.20.101.2
        int-sdsevo-lb2:
          ansible_host: 172.20.101.3
        int-sdsevo-msg1:
          ansible_host: 172.20.101.46
        int-sdsevo-msg2:
          ansible_host: 172.20.101.47
        int-sdsevo-msg3:
          ansible_host: 172.20.101.48
        int-sdsevo-ng1:
          ansible_host: 172.20.101.4
        int-sdsevo-ng2:
          ansible_host: 172.20.101.5
        int-sdsevo-oltp1:
          ansible_host: 172.20.101.49
        int-sdsevo-repl1:
          ansible_host: 172.20.101.50
        int-sdsevo-repl2:
          ansible_host: 172.20.101.51
        int-sdsevo-web1:
          ansible_host: 172.20.101.42
        int-sdsevo-web2:
          ansible_host: 172.20.101.43
        prod-sdsevo-app1:
          ansible_host: 172.20.101.10
        prod-sdsevo-app2:
          ansible_host: 172.20.101.11
        prod-sdsevo-cache1:
          ansible_host: 172.20.101.30
        prod-sdsevo-cache2:
          ansible_host: 172.20.101.31
        prod-sdsevo-cache3:
          ansible_host: 172.20.101.32
        prod-sdsevo-cdn1:
          ansible_host: 172.20.101.20
        prod-sdsevo-cdn2:
          ansible_host: 172.20.101.21
        prod-sdsevo-dwh1:
          ansible_host: 172.20.101.29
        prod-sdsevo-lb1:
          ansible_host: 172.20.101.105
        prod-sdsevo-lb2:
          ansible_host: 172.20.101.6
        prod-sdsevo-msg1:
          ansible_host: 172.20.101.22
        prod-sdsevo-msg2:
          ansible_host: 172.20.101.23
        prod-sdsevo-msg3:
          ansible_host: 172.20.101.24
        prod-sdsevo-oltp1:
          ansible_host: 172.20.101.25
        prod-sdsevo-repl1:
          ansible_host: 172.20.101.26
        prod-sdsevo-repl2:
          ansible_host: 172.20.101.27
        prod-sdsevo-repl3:
          ansible_host: 172.20.101.28
        prod-sdsevo-web1:
          ansible_host: 172.20.101.12
        prod-sdsevo-web2:
          ansible_host: 172.20.101.13
        prod-sdsevo-web3:
          ansible_host: 172.20.101.14
        prod-sdsevo-web4:
          ansible_host: 172.20.101.15
        prod-sdsevo-web5:
          ansible_host: 172.20.101.16
        prod-sdsevo-web6:
          ansible_host: 172.20.101.17
        prod-sdsevo-web7:
          ansible_host: 172.20.101.18
        prod-sdsevo-web8:
          ansible_host: 172.20.101.19
        prod-sdsevo-monitoring1:
          ansible_host: 172.20.164.34

    elive:
      hosts:
        int-elive-cdn01:
          ansible_host: 172.20.181.16
        int-elive-cdn02:
          ansible_host: 172.20.181.18
        int-elive-lb01:
          ansible_host: 172.20.181.20
        int-elive-lb02:
          ansible_host: 172.20.181.21
        int-elive-origin01:
          ansible_host: 172.20.181.17
        int-elive-origin02:
          ansible_host: 172.20.181.19
        prod-elive-cdn01:
          ansible_host: 172.20.165.15
        prod-elive-cdn02:
          ansible_host: 172.20.165.17
        prod-elive-lb01:
          ansible_host: 172.20.165.19
        prod-elive-lb02:
          ansible_host: 172.20.165.20
        prod-elive-origin01:
          ansible_host: 172.20.165.16
        prod-elive-origin02:
          ansible_host: 172.20.165.18
        int-elive-enc-mgt:
          ansible_host: 172.20.100.3
        prod-elive-enc-mgt:
          ansible_host: 172.20.100.2

    vas:
      hosts:
        prod-vas1:
          ansible_host: 62.113.39.226
        prod-vas2:
          ansible_host: 62.113.39.227
        prod-vas3:
          ansible_host: 62.113.39.228
        prod-vas4:
          ansible_host: 62.113.39.229
        vas-lb1:
          ansible_host: 62.113.39.230
        vas-lb2:
          ansible_host: 62.113.39.231

    xrm:
      hosts:
        int-xrm1:
          ansible_host: 172.20.102.10
        int-xrm2:
          ansible_host: 172.20.102.11
        prod-xrm-mon:
          ansible_host: 172.20.102.24
        prod-xrm1:
          ansible_host: 172.20.102.20
        prod-xrm2:
          ansible_host: 172.20.102.21
        prod-xrm3:
          ansible_host: 172.20.102.22
        prod-xrm4:
          ansible_host: 172.20.102.23
        lb-xrm-1:
          ansible_host: 172.20.102.101
        lb-xrm-2:
          ansible_host: 172.20.102.102
        prod-xrm1-2024:
          ansible_host: 172.20.102.30
        prod-xrm2-2024:
          ansible_host: 172.20.102.31
        prod-xrm3-2024:
          ansible_host: 172.20.102.32
        prod-xrm4-2024:
          ansible_host: 172.20.102.33
        int-xrm1-2024:
          ansible_host: 172.20.102.11

    arni:
      hosts:
        db1-prod:
          ansible_host: 172.20.104.10
        db2-prod:
          ansible_host: 172.20.104.20
        db3-prod:
          ansible_host: 172.20.104.30
        app1-prod:
          ansible_host: 172.20.104.11
        sslproxy1-prod:
          ansible_host: 172.20.104.12
        db1-int:
          ansible_host: 172.20.104.9
        db2-int:
          ansible_host: 172.20.104.21
        db3-int:
          ansible_host: 172.20.104.31
        app1-int:
          ansible_host: 172.20.104.41
        sslproxy1-int:
          ansible_host: 172.20.104.13
        vod-generator:
          ansible_host: 172.20.104.14
        build.prod.lan:
          ansible_host: 172.20.104.51
        build.int.lan:
          ansible_host: 172.20.104.52

    zabbix:
      hosts:
        zabbix-prod:
          ansible_host: 172.20.171.110
        zabbix-lab:
          ansible_host: 192.168.20.248

    proxmox:
      children:
        pve-office:
          hosts:
            pve-211:
              ansible_host: 192.168.88.211
            pve-212:
              ansible_host: 192.168.88.212
            pve-213:
              ansible_host: 192.168.88.213
        pve-m9:
          hosts:
            pve-111:
              ansible_host: 172.20.161.111
            pve-112:
              ansible_host: 172.20.161.112
            pve-113:
              ansible_host: 172.20.161.113
            pve-114:
              ansible_host: 172.20.161.114
            pve-115:
              ansible_host: 172.20.161.115
            pve-116:
              ansible_host: 172.20.161.116
            pve-117:
              ansible_host: 172.20.161.117
            pve-118:
              ansible_host: 172.20.161.118
        pve-out:
          hosts:
            pve-214:
              ansible_host: 192.168.88.214
        pbs:
          hosts:
            pbs-lab:
              ansible_host: 192.168.88.250
            pbs-reserv:
              ansible_host: 192.168.88.253
            pbs-m9:
              ansible_host: 172.20.161.250
        pdm:
          hosts:
            pdm-prod:
              ansible_host: 172.20.161.120

    zappware:
      hosts:
        int-monitoring1:
          ansible_host: 172.20.101.57
        int-analytics1:
          ansible_host: 172.20.101.56
        prod-analytics1:
          ansible_host: 172.20.101.33

    other-prod:
      hosts:
        greenbone:
          ansible_host: 172.20.104.95
        gitlab:
          ansible_host: 192.168.21.12
          ansible_port: 2222
        wazuh:
          ansible_host: 192.168.21.190
        elk-prod:
          ansible_host: 192.168.21.15
        mattermost:
          ansible_host: 192.168.21.16
        jira-service-desk:
          ansible_host: 192.168.21.17
        confluence:
          ansible_host: 192.168.21.18

    other-lab:
      hosts:
        nextcloud:
          ansible_host: 192.168.20.102
        awx:
          ansible_host: 192.168.20.103
        checklist:
          ansible_host: 192.168.20.7
        report:
          ansible_host: 192.168.20.8

    cdn:
      hosts:
        int-cdn-tv:
          ansible_host: 172.20.101.59
        prod-cdn-tv:
          ansible_host: 172.20.101.35

