---
- name: Настраиваем Production
  hosts: "*prod*"
  become: yes
  vars_files:
    - /etc/ansible/secret.yml
  roles: 
    - manage_users
#    - disable_ipv6
#    - ntp_setup
#    - zabbix-agent_setup
#    - auditd_setup
