- name: Настраиваем линух
  hosts: awx
  become: true
  roles:
#    - qemu-agent_setup
#    - manage_users
#    - disable_ipv6
#    - ntp_setup
#    - certs_setup
    - zabbix-agent_setup
#    - postfix_setup
#    - auditd_setup
#    - filebeat_setup
#    - fail2ban_setup
#    - network_security
#    - wazuh-agent_setup
#    - clamav_wazuh_setup
#    - lmd_setup
#    - iptables_setup
